### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by lucas34** [zendesk/belvedere#19]
Hi,

I'm using the version 1.2.0.1-SNAPSHOT.
But It seems like you deleted this version from your repo. It's the only version that have the PR #11 included. So now, What is the latest that also include the PR for opening should showing the dialog ?

Regards,
Lucas.

**Comment by brendan-fahy** [comment]
Hey @lucas34,

Thanks for reporting this. We had an issue with Jfrog/artifactoryonline yesterday, an outage that required us to do some rebuilding of virtual repos. It looks like we missed a couple of things, including the latest release and snapshot artefacts of Belvedere. We've re-added those virtual repos now, so you should be able to access 1.2.0.1-SNAPSHOT again. Can you retry and verify that you can access it again? 

I didn't realise people were using a snapshot version, we might look at pushing a 1.2.0.1 release so you don't have to use a snapshot. 

Thanks,

Brnedan

**Comment by lucas34** [comment]
Hi,

Yep, it's okay.

Thanks for the quick reply.

**Comment by schlan** [comment]
Hi @lucas34, we just release v1.2.0.1.
