### ISSUE TITLE
Building locally?

### ISSUE THREAD

**Issue by dkr88** [zendesk/belvedere#8]
Question: How can I build the belvedere library in Android Studio so that I can test some changes locally? When I generate the aar and reference it as a module in my own app the dialog does not open when calling .openDialog(activityManager) - but there are no errors...

I can only wonder if it's something relating to the manifest merging? Sorry I'm quite new to Android development so any guidance you can provide would be appreciated.

EDIT: Nevermind - error on my part.

**Comment by schlan** [comment]
Cool, I'll close the issue. Open a new one if you find further issues.
