### ISSUE TITLE
Can't open gallery with image and video

### ISSUE THREAD

**Issue by dudejohn** [zendesk/belvedere#80]
how to open gallery with image and video?

**Comment by schlan** [comment]
At the moment the image stream only shows images. Allowing the user to select images and videos through the document intent is not possible. That's a restriction by the Android system. As workaround you can allow the user to select any content type and filter the results afterwards.

```
BelvedereUi.imageStream(this)
    .withDocumentIntent("*/*", true)
    .showPopup(this);
```
